sub soh_format {
  $outfile = shift @_;
  %h = @_;
  print_head("$outfile","EPS", %h);

open (SF, ">>$outfile");

printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>Load Bus</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>Solar Array</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>EPS SW</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ELBV</FONT></TD>\n", ${$h{ELBV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{ELBV}}[3], ${$h{ELBV}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ESAMYI</FONT></TD>\n", ${$h{ESAMYI}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{ESAMYI}}[3], ${$h{ESAMYI}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EGCTTEL1</FONT></TD>\n", ${$h{EGCTTEL1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EGCTTEL1}}[3], ${$h{EGCTTEL1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ELBI_LOW</FONT></TD>\n", ${$h{ELBI_LOW}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{ELBI_LOW}}[3], ${$h{ELBI_LOW}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>TSAMYT</FONT></TD>\n", ${$h{TSAMYT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{TSAMYT}}[3], ${$h{TSAMYT}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EGCTTEL3</FONT></TD>\n", ${$h{EGCTTEL3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EGCTTEL3}}[3], ${$h{EGCTTEL3}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ELDBCRNG</FONT></TD>\n", ${$h{ELDBCRNG}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ELDBCRNG}}[3], ${$h{ELDBCRNG}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ESAPYI</FONT></TD>\n", ${$h{ESAPYI}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{ESAPYI}}[3], ${$h{ESAPYI}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EPSTATE</FONT></TD>\n", ${$h{EPSTATE}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EPSTATE}}[3], ${$h{EPSTATE}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>POWER</FONT></TD>\n", ${$h{POWER}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{POWER}}[3], ${$h{POWER}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>TSAPYT</FONT></TD>\n", ${$h{TSAPYT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{TSAPYT}}[3], ${$h{TSAPYT}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EECLIPSE</FONT></TD>\n", ${$h{EECLIPSE}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EECLIPSE}}[3], ${$h{EECLIPSE}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EESAILLM</FONT></TD>\n", ${$h{EESAILLM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EESAILLM}}[3], ${$h{EESAILLM}}[1];

printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";

printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>Battery 1</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>Battery 2</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>Battery 3</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 1 VOLTAGE V<br><font color=#FFFF00>(27.0) 31.0 </font><br><font color=#FF0000>(26.0) 31.0</font>', CAPTION, 'EB1V' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB1V</FONT></a></TD>\n", ${$h{EB1V}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{EB1V}}[3], ${$h{EB1V}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 2 VOLTAGE V<br><font color=#FFFF00>(27.0) 31.0 </font><br><font color=#FF0000>(26.0) 31.0</font>', CAPTION, 'EB2V' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB2V</FONT></a></TD>\n", ${$h{EB2V}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{EB2V}}[3], ${$h{EB2V}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 3 VOLTAGE V<br><font color=#FFFF00>(27.0) 31.0 </font><br><font color=#FF0000>(26.0) 31.0</font>', CAPTION, 'EB3V' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB3V</FONT></a></TD>\n", ${$h{EB3V}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{EB3V}}[3], ${$h{EB3V}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 1 CHARGE CURRENT AMP<br><font color=#FFFF00>(0.0) 0.1 </font><br><font color=#FF0000>(-1.0) 0.1</font>', CAPTION, 'EB1CI' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB1CI</FONT></a></TD>\n", ${$h{EB1CI}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{EB1CI}}[3], ${$h{EB1CI}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 2 CHARGE CURRENT AMP<br><font color=#FFFF00>(0.0) 0.1 </font><br><font color=#FF0000>(-1.0) 0.1</font>', CAPTION, 'EB2CI' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB2CI</FONT></a></TD>\n", ${$h{EB2CI}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{EB2CI}}[3], ${$h{EB2CI}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 3 CHARGE CURRENT AMP<br><font color=#FFFF00>(0.0) 0.1 </font><br><font color=#FF0000>(-1.0) 0.1</font>', CAPTION, 'EB3CI' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB3CI</FONT></a></TD>\n", ${$h{EB3CI}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{EB3CI}}[3], ${$h{EB3CI}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 1 DISCHARGE CURRENT AMP<br><font color=#FFFF00>(0.0) 1.0 </font><br><font color=#FF0000>(-1.0) 1.0</font>', CAPTION, 'EB1DI' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB1DI</FONT></a></TD>\n", ${$h{EB1DI}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{EB1DI}}[3], ${$h{EB1DI}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 2 DISCHARGE CURRENT AMP<br><font color=#FFFF00>(0.0) 1.0 </font><br><font color=#FF0000>(-1.0) 1.0</font>', CAPTION, 'EB2DI' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB2DI</FONT></a></TD>\n", ${$h{EB2DI}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{EB2DI}}[3], ${$h{EB2DI}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 3 DISCHARGE CURRENT AMP<br><font color=#FFFF00>(0.0) 1.0 </font><br><font color=#FF0000>(-1.0) 1.0</font>', CAPTION, 'EB3DI' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB3DI</FONT></a></TD>\n", ${$h{EB3DI}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{EB3DI}}[3], ${$h{EB3DI}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>TB1T1</FONT></TD>\n", ${$h{TB1T1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{TB1T1}}[3], ${$h{TB1T1}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>TB2T1</FONT></TD>\n", ${$h{TB2T1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{TB2T1}}[3], ${$h{TB2T1}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>TB3T1</FONT></TD>\n", ${$h{TB3T1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{TB3T1}}[3], ${$h{TB3T1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>TB1T2</FONT></TD>\n", ${$h{TB1T2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{TB1T2}}[3], ${$h{TB1T2}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>TB2T2</FONT></TD>\n", ${$h{TB2T2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{TB2T2}}[3], ${$h{TB2T2}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>TB3T2</FONT></TD>\n", ${$h{TB3T2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{TB3T2}}[3], ${$h{TB3T2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>TB1T3</FONT></TD>\n", ${$h{TB1T3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{TB1T3}}[3], ${$h{TB1T3}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>TB2T3</FONT></TD>\n", ${$h{TB2T3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{TB2T3}}[3], ${$h{TB2T3}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>TB3T3</FONT></TD>\n", ${$h{TB3T3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{TB3T3}}[3], ${$h{TB3T3}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 1 K1 STATUS <br>  OPEN CLOS', CAPTION, 'EB1K1' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB1K1</FONT></a></TD>\n", ${$h{EB1K1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EB1K1}}[3], ${$h{EB1K1}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 2 K1 STATUS <br>  OPEN CLOS', CAPTION, 'EB2K1' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB2K1</FONT></a></TD>\n", ${$h{EB2K1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EB2K1}}[3], ${$h{EB2K1}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 3 K1 STATUS <br>  OPEN CLOS', CAPTION, 'EB3K1' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB3K1</FONT></a></TD>\n", ${$h{EB3K1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EB3K1}}[3], ${$h{EB3K1}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 1 K2 STATUS <br>  OPEN CLOS', CAPTION, 'EB1K2' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB1K2</FONT></a></TD>\n", ${$h{EB1K2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EB1K2}}[3], ${$h{EB1K2}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 2 K2 STATUS <br>  OPEN CLOS', CAPTION, 'EB2K2' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB2K2</FONT></a></TD>\n", ${$h{EB2K2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EB2K2}}[3], ${$h{EB2K2}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 3 K2 STATUS <br>  OPEN CLOS', CAPTION, 'EB3K2' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB3K2</FONT></a></TD>\n", ${$h{EB3K2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EB3K2}}[3], ${$h{EB3K2}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 1 K3 STATUS <br>  BYK2 BYK1', CAPTION, 'EB1K3' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB1K3</FONT></a></TD>\n", ${$h{EB1K3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EB1K3}}[3], ${$h{EB1K3}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 2 K3 STATUS <br>  BYK2 BYK1', CAPTION, 'EB2K3' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB2K3</FONT></a></TD>\n", ${$h{EB2K3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EB2K3}}[3], ${$h{EB2K3}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 3 K3 STATUS <br>  BYK2 BYK1', CAPTION, 'EB3K3' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB3K3</FONT></a></TD>\n", ${$h{EB3K3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EB3K3}}[3], ${$h{EB3K3}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 1 K4 STATUS <br>  OVRT NORM', CAPTION, 'EB1K4' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB1K4</FONT></a></TD>\n", ${$h{EB1K4}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EB1K4}}[3], ${$h{EB1K4}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 2 K4 STATUS <br>  OVRT NORM', CAPTION, 'EB2K4' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB2K4</FONT></a></TD>\n", ${$h{EB2K4}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EB2K4}}[3], ${$h{EB2K4}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 3 K4 STATUS <br>  OVRT NORM', CAPTION, 'EB3K4' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB3K4</FONT></a></TD>\n", ${$h{EB3K4}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EB3K4}}[3], ${$h{EB3K4}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 1 K5 STATUS <br>  OFF ON', CAPTION, 'EB1K5' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB1K5</FONT></a></TD>\n", ${$h{EB1K5}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EB1K5}}[3], ${$h{EB1K5}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 2 K5 STATUS <br>  OFF ON', CAPTION, 'EB2K5' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB2K5</FONT></a></TD>\n", ${$h{EB2K5}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EB2K5}}[3], ${$h{EB2K5}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 3 K5 STATUS <br>  OFF ON', CAPTION, 'EB3K5' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB3K5</FONT></a></TD>\n", ${$h{EB3K5}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EB3K5}}[3], ${$h{EB3K5}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 1 K6/K7 UV PROT <br>  DISA ENAB', CAPTION, 'EB1UV' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB1UV</FONT></a></TD>\n", ${$h{EB1UV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EB1UV}}[3], ${$h{EB1UV}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 2 K6/K7 UV PROT <br>  ENAB DISA', CAPTION, 'EB2UV' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB2UV</FONT></a></TD>\n", ${$h{EB2UV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EB2UV}}[3], ${$h{EB2UV}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 3 K6/K7 UV PROT <br>  ENAB DISA', CAPTION, 'EB3UV' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB3UV</FONT></a></TD>\n", ${$h{EB3UV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EB3UV}}[3], ${$h{EB3UV}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EOCHRGB1</FONT></TD>\n", ${$h{EOCHRGB1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{EOCHRGB1}}[3], ${$h{EOCHRGB1}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EOCHRGB2</FONT></TD>\n", ${$h{EOCHRGB2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{EOCHRGB2}}[3], ${$h{EOCHRGB2}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EOCHRGB3</FONT></TD>\n", ${$h{EOCHRGB3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{EOCHRGB3}}[3], ${$h{EOCHRGB3}}[1];

printf SF "</TABLE>\n";

printf SF "<BR>\n";
close SF;

print_links("$outfile");
open (SF,">>$outfile");
print SF "</BODY></HTML>\n";
close SF;
# end
}
1;
